# Generated by Django 4.1.7 on 2023-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Soap', 'Soap'), ('Detergent', 'Detergent')], max_length=40),
        ),
    ]
