# Generated by Django 4.1.7 on 2023-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_alter_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='general_product')),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
