# Generated by Django 4.1.7 on 2023-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_womenssaree_womensshoes_womenswatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=40)),
            ],
        ),
    ]
