# Generated by Django 4.1.7 on 2023-05-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_allproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProduct',
        ),
    ]
