# Generated by Django 4.1.7 on 2023-05-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_allproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='cat',
            field=models.CharField(choices=[('MensShirt', 'MensShirt'), ('MensShoe', 'MensShoe'), ('WomensJacket', 'WomensJacket'), ('KidsToy', 'KidsToy')], max_length=30),
        ),
    ]
