# Generated by Django 4.1.7 on 2023-05-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0014_alter_allproduct_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='cat',
            new_name='category',
        ),
    ]
