# Generated by Django 4.1.7 on 2023-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0016_eachproductimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='category',
            field=models.CharField(choices=[('MensShirt', 'MensShirt'), ('MensTshirt', 'MensTshirt'), ('MensShoe', 'MensShoe'), ('WomensJacket', 'WomensJacket'), ('KidsToy', 'KidsToy')], max_length=30),
        ),
    ]
