# Generated by Django 4.1.7 on 2023-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0017_alter_allproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='category',
            field=models.CharField(choices=[('MensShirt', 'MensShirt'), ('MensTshirt', 'MensTshirt'), ('WomensJacket', 'WomensJacket'), ('WomensSaree', 'WomensSaree'), ('KidsToy', 'KidsToy')], max_length=30),
        ),
    ]
