# Generated by Django 4.1.7 on 2023-05-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0019_alter_allproduct_category_costumer_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
