# Generated by Django 4.1.7 on 2023-05-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0022_orderplaced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumerDetail',
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.DeleteModel(
            name='MensShoes',
        ),
        migrations.DeleteModel(
            name='MensWatches',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.RemoveField(
            model_name='shirtonetoone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tshirtonetoone',
            name='user',
        ),
        migrations.DeleteModel(
            name='WomensJackets',
        ),
        migrations.DeleteModel(
            name='WomensSaree',
        ),
        migrations.DeleteModel(
            name='WomensShoes',
        ),
        migrations.DeleteModel(
            name='WomensWatches',
        ),
        migrations.DeleteModel(
            name='MensShits',
        ),
        migrations.DeleteModel(
            name='MensTshits',
        ),
        migrations.DeleteModel(
            name='ShirtOnetoOne',
        ),
        migrations.DeleteModel(
            name='TshirtOnetoOne',
        ),
    ]
